const supportTelegramHandle = '@entrance_tricks_admin';
const supportTelegramUrl = 'https://t.me/entrance_tricks_admin';
const supportPhoneNumber = '0920308061';
const supportPhoneUrl = 'tel:0920308061';
const supportEmail = 'entrancetricks@gmail.com';
const supportEmailUrl =
    'mailto:entrancetricks@gmail.com?subject=Entrance%20Tricks%20Support';
const supportWebsiteHost = 'entrancetricks.com';
const supportWebsiteUrl = 'https://entrancetricks.com';
